### ISSUE TITLE
TeleOp Arm Control does not stop when it reaches TargetPosition

### ISSUE THREAD

**Issue by Carl4** [innovators3311/FreightFrenzy_Official#1]
When using [DC Motors in the RUN_TO_POSITION mode](https://ftctechnh.github.io/ftc_app/doc/javadoc/index.html?com/qualcomm/robotcore/hardware/DcMotor.RunMode.html) in TelleOp mode, the arm motors sit idle until a change in target encoder value is applied and the setPower() function is called.  The motor moves in the appropriate direction, but then continues in that direction forever.  All available documentation suggests that the PID Motor modes are designed to stop when they reach the target encoder value. Not sure why this isn't happening, but we have some suspicions.

**Comment by Carl4** [comment]
Possible reason:  The DcMotor class is expecting to be able to update the motor power at a regular cadence (e.g. inside the loop) but is not able to do so.  
1. Is there a periodic motor power update we need to call at some regular cadence? 
2. Are we supposed to call something like ifle() inside our loop to allow other threads to run (e.g. in a cooperative multithreading model)?

**Comment by Carl4** [comment]
[This example code](https://github.com/Pattonville-Robotics/7856/wiki/How-to-Write-Robot-Opmodes#tele-op) has an `idle();` call inside their while loop.  I have been unable to find the `LinearOpMode`  java file, so I'm not sure how `loop()` is implemented in `OpMode`.  
* The examples I've found where idle() is called all seem to be in classes that extend `LinearOpMode`. Possible that `OpMode`'s loop function already implements the idle(); command. 
* Also, [OpMode doesn't appear to have an idle methid](https://ftctechnh.github.io/ftc_app/doc/javadoc/com/qualcomm/robotcore/eventloop/opmode/OpMode.html)

Much of the inspiration for the TeleOp mode drive functionality comes from: 
* [PushbodAutoDriveByEncoder](https://github.com/innovators3311/FreightFrenzy_Official/blob/master/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/PushbotAutoDriveByEncoder_Linear.java#L157) with the caveat that we're using an `OpMode` rather than a `LinearOpMode`, so:
  * The while loop is implemented for us
  * We don't have `wait()` or `opModeIsActive()` methods we can call.
  * I really wish I could see how `LinearOpMode` extends `OpMode`, but the code doesn't seem to be published.

**Comment by BrendanFish** [comment]
Looks like the solution to the PID-mode problem we're having may be to reverse the motor polarity (swap black and red wires)

**Comment by Carl4** [comment]
Found this document at rev robotics.  It's written for the graphical programming language, but should map 1:1 to java. 

https://docs.revrobotics.com/rev-control-system/programming/using-encoder-feedback#using-run_to_position

**Comment by BrendanFish** [comment]
fixed
